# Generated by Django 4.2.13 on 2024-06-12 10:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plant',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
