# Generated by Django 4.2.13 on 2024-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_managers_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='watering',
            name='litres',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
