# Generated by Django 4.2.13 on 2024-09-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plantfamilies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlantFamilies',
            new_name='PlantFamily',
        ),
    ]
