# Generated by Django 4.2.13 on 2024-09-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_rename_plantfamilies_plantfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='family', to='plants.plantfamily'),
            preserve_default=False,
        ),
    ]
