# Generated by Django 4.2.13 on 2024-06-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_rename_waterings_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watering',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterings', to='plants.plant'),
        ),
    ]
